server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/products {
        proxy_pass http://products:3001;
        proxy_set_header Host $host;
    }

    location /api/categories {
        proxy_pass http://products:3001;
        proxy_set_header Host $host;
    }

    location /uploads {
        proxy_pass http://products:3001;
        proxy_set_header Host $host;
    }

    location /api/cart {
        proxy_pass http://orders:3002;
        proxy_set_header Host $host;
    }

    location /api/orders {
        proxy_pass http://orders:3002;
        proxy_set_header Host $host;
    }

    location /api/admin {
        proxy_pass http://admin:3003;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
